import mongoose from 'mongoose';

const workHistoryEntrySchema = new mongoose.Schema({
    company:        { type: String, required: true },
    title:          { type: String, required: true },
    department:     String,
    location:       String,
    startDate:      { type: Date, required: true },
    endDate:        Date,
    isCurrent:      Boolean,
    employmentType: { type: String, required: true },
    description:    String,
    achievements:   { type: [String], required: true },
    skillsUsed:     { type: [String], required: true }
}, { _id: false });

const educationEntrySchema = new mongoose.Schema({
    level:        { type: String, required: true },
    institution:  { type: String, required: true },
    degree:       { type: String, required: true },
    fieldOfStudy: String,
    year:         { type: Number, required: true },
    gradeOrGpa:   String,
    duration:     String
}, { _id: false });

const resumeSchema = new mongoose.Schema({

    userId:      { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    isActive:    Boolean,
    isComplete:  Boolean,
    templateId:  { type: mongoose.Schema.Types.ObjectId, ref: 'ResumeTemplate' },
    personaCode: String,

    personal: {
        fullName:               { type: String, required: true },
        preferredName:          String,
        surname:                String,
        middleName:             String,
        profileTitle:           String,
        dateOfBirth:            { type: Date },
        placeOfBirth:           String,
        gender:                 String,
        maritalStatus:          String,
        nationality:            String,
        citizenship:            String,
        religion:               String,
        community:              String,
        nativePlace:            String,
        fatherName:             String,
        motherName:             String,
        guardianName:           String,
        languagesKnown:         [String],
        profilePhoto:           String,
        personalIntroVideo:     String,
        personalTagline:        String,
        email:                  String,
        alternateEmail:         String,
        contactNumber:          String,
        alternateContactNumber: String,
        whatsappNumber:         String,
        emergencyContactName:   String,
        emergencyContactNumber: String,
        address:                String,
        city:                   String,
        stateProvince:          String,
        country:                String,
        postalCode:             String,
        currentLocation:        String,
        preferredLocation:      [String],
        residenceType:          String,
        timeZone:               String
    },

    summary: {
        careerObjective:          String,
        professionalSummary:      String,
        personalStatement:        String,
        careerHighlights:         [String],
        keyAchievements:          [String],
        elevatorPitch:            String,
        careerMission:            String,
        careerVision:             String,
        valueProposition:         String,
        professionalHeadline:     String,
        executiveSummary:         String,
        careerChangeReason:       String,
        employmentGapExplanation: String,
        portfolioSummary:         String
    },

    experience: {
        jobCategorySlug:            String,
        jobGroupSlug:               String,
        jobRoleSlug:                String,
        experienceLevelSlug:        String,
        workModeSlug:               String,
        currentDesignation:         String,
        currentCompany:             String,
        desiredJobTitle:            String,
        yearsOfExperience:          Number,
        employmentType:             String,
        availabilityDate:           Date,
        noticePeriod:               String,
        lastWorkingDay:             Date,
        expectedSalary:             String,
        currentSalary:              String,
        minimumSalary:              String,
        salaryCurrency:             String,
        salaryFrequency:            String,
        targetIndustry:             [String],
        targetCompanyType:          String,
        targetSeniority:            String,
        preferredDepartment:        String,
        preferredShift:             String,
        industryExperience:         [String],
        previousCompanies:          [String],
        responsibilities:           [String],
        projectsHandled:            [String],
        clientsServed:              [String],
        totalProjects:              Number,
        teamSizeHandled:            Number,
        directReports:              Number,
        budgetHandled:              String,
        reportingTo:                String,
        workAuthorizationCountries: [String],
        openToContract:             Boolean,
        openToInternship:           Boolean,
        openToPartTime:             Boolean,
        openToNightShift:           Boolean,
        openToFieldWork:            Boolean,
        openToOffshoreWork:         Boolean,
        openToOverseasWork:         Boolean
    },

    workHistory: [workHistoryEntrySchema],

    education: {
        educationLevelSlug:    String,
        highestEducation:      String,
        educationMode:         String,
        thesisTitle:           String,
        researchArea:          String,
        academicTranscriptUrl: String,
        academicAchievements:  [String],
        entries:               [educationEntrySchema]
    },

    skills: {
        technicalSkills:       [String],
        softSkills:            [String],
        computerSkills:        [String],
        softwareTools:         [String],
        analyticalSkills:      [String],
        problemSolvingSkills:  [String],
        decisionMakingSkills:  [String],
        leadershipSkills:      [String],
        communicationSkills:   [String],
        languageSkills:        [String],
        languageProficiency:   [String],
        professionalSkills:    [String],
        tradeSkills:           [String],
        toolSkills:            [String],
        equipmentSkills:       [String],
        safetySkills:          [String],
        managementSkills:      [String],
        salesSkills:           [String],
        customerServiceSkills: [String],
        financeSkills:         [String],
        healthcareSkills:      [String],
        teachingSkills:        [String],
        creativeSkills:        [String],
        digitalSkills:         [String],
        typingSpeed:           String
    },

    additional: {
        certifications:          [String],
        licenses:                [String],
        trainingCourses:         [String],
        safetyCourses:           [String],
        trainingInstitute:       String,
        trainingCompletionDate:  Date,
        certificationAuthority:  String,
        certificationNumber:     String,
        certificationIssueDate:  Date,
        certificationExpiryDate: Date,
        licenseNumber:           String,
        licenseIssueDate:        Date,
        licenseExpiryDate:       Date,
        issuingCountry:          String,
        passportDetails:         String,
        passportNumber:          String,
        passportExpiryDate:      Date,
        visaStatus:              String,
        visaExpiryDate:          Date,
        workPermit:              String,
        workPermitExpiryDate:    Date,
        drivingLicense:          String,
        seamanBook:              String,
        idProofType:             String,
        idProofNumber:           String,
        taxId:                   String,
        policeClearance:         String,
        backgroundCheckStatus:   String,
        willingnessToTravel:     Boolean,
        willingnessToRelocate:   Boolean,
        shiftPreference:         String,
        remoteWorkPreference:    String,
        preferredWorkHours:      String,
        uploadedResume:          String,
        documentUploadUrl:       String,
        resumeDownloadUrl:       String,
        coverLetterUrl:          String,
        referenceName:           String,
        referenceContact:        String,
        referenceRelationship:   String,
        references:              String,
        hobbies:                 [String],
        volunteerWork:           String,
        awards:                  [String],
        publications:            [String],
        customNotes:             String
    },

    health: {
        physicalFitness: String,
        medicalFitness:  String,
        height:          String,
        weight:          String,
        bloodGroup:      String
    },

    traits: {
        discipline:     String,
        stressHandling: String,
        teamwork:       String,
        adaptability:   String,
        workEthic:      String
    },

    links: {
        linkedinProfile:     String,
        githubProfile:       String,
        portfolioWebsite:    String,
        personalWebsite:     String,
        personalBlog:        String,
        behanceProfile:      String,
        dribbbleProfile:     String,
        stackoverflowProfile:String,
        youtubeChannel:      String,
        instagramProfile:    String,
        facebookProfile:     String,
        twitterProfile:      String,
        mediumProfile:       String,
        researchGateProfile: String,
        socialMediaLinks:    [String]
    }

}, { timestamps: true });

resumeSchema.index({ 'experience.jobCategorySlug':   1 });
resumeSchema.index({ 'experience.jobRoleSlug':        1 });
resumeSchema.index({ 'experience.experienceLevelSlug': 1 });
resumeSchema.index({ 'experience.workModeSlug':       1 });
resumeSchema.index({ 'personal.country':              1 });
resumeSchema.index({ isActive: 1, updatedAt: -1 });

export const Resume = mongoose.model('Resume', resumeSchema);
